data: "data/test_data.csv"
nsamples_prevalence_map: 3000
end_sim_year: 2019
AMIS:
  smooth_param: 0.01
  nsamples: 500
  mixture_samples: 1000
  df: 3
  target_ess_size: 500
  log_scale: False
  max_iterations: 30
nsamples_beta: 200
