data: "data/FinalDataTest.csv"
nsamples_prevalence_map: 1000
end_sim_year: 2019
AMIS:
  smooth_param: 0.01
  nsamples: 10
  mixture_samples: 1000
  df: 3
  target_ess_size: 500
  log_scale: False
  max_iterations: 2
nsamples_beta: 10
